### ISSUE TITLE
Separate development settings from production settings

### ISSUE THREAD

**Issue by vmalloc** [getweber/cob#27]
# Configuration Locations
Cob should load configuration from three different locations:

1. Project's config
2. (if exists) - `/etc/cob/conf.d/<project-name>`
3. The user's `~/.config/cob/projects/<project-name>`

The above are ordered, so the last loaded config takes precedence.

This will let users set up localized configuration in their homedir, and secret/project-specific configuration on the server being deployed

# Deployment vs. Development
Configuration should support overlays for production vs. development. One way we can do this is through an "overlays" section of the configuration. For instance:

```
# .cob-project.yml
flask_config:
   ...
overlays:
   develop:
       flask_config:
          SQLALCHEMY_ECHO: true
   production:
      flask_config:
          SECRET_VALUE: 2
```
This way cob automatically uses "production" when deploying the project, letting the user customize it how he or she pleases. 

Also, it should be possible to create and use custom overlays, which can be applied whenever necessary.
